name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || pip install fastapi uvicorn[standard] sqlalchemy psycopg2-binary
      - name: Lint (flake8)
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 .
      - name: Test (placeholder)
        run: echo "No backend tests yet"

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint (eslint)
        run: npx eslint . || echo "No ESLint config yet"
      - name: Build
        run: npm run build
      - name: Test (placeholder)
        run: echo "No frontend tests yet" 